name: Test and Build

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - name: Lint
        run: |
          yarn run check:eslint
          yarn run check:prettier
      - run: yarn test
      - run: yarn run build:lib
      - run: yarn pack
      - name: Upload the package as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-ymd-date-select
          path: react-ymd-date-select*.tgz
      - name: Draft a new release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') && startsWith(matrix.node-version, '16.')
        with:
          draft: true
          files: react-ymd-date-select*.tgz
